### ISSUE TITLE
Fix type regression in `tsnext` which throws `TS2463`

### ISSUE THREAD

**Issue by voxpelli** [voxpelli/pony-cause#45]
The `tsnext` tests are now failing: https://github.com/voxpelli/pony-cause/runs/7605089081?check_suite_focus=true

> index.js(9,25): error TS2463: A binding pattern parameter cannot be optional in an implementation signature.

Happens at: https://github.com/voxpelli/pony-cause/blob/4009048a41d772cb29673f1c45cc55e9717e523f/lib/error-with-cause.js#L5-L9

Likely caused by:

- https://github.com/microsoft/TypeScript/pull/50094
- https://github.com/microsoft/TypeScript/pull/49869

Spontaneous thought is that TS has regressed rather than this being a correct error, but have to dig into it.

**Comment by sandersn** [comment]
The TS equivalent, `function test(everything? = '') { }` is illegal:

TS1015 Parameter cannot have question mark and initializer.

In the JS below, `options` is marked as optional by the type system:

```js
/**
 * @param {string} filled
 * @param {{ cause?: string }} options
 */
function test(filled, { cause } = {}) {
}
```

So the question is whether the duplicate marking of optionality should be legal in JS where it is illegal in TS. If it's illegal, then there needs to be an error for it same as in TS.

**Comment by voxpelli** [comment]
@sandersn In think its a bit harsh to error on duplicate marking of optionality, I myself quite like it and its not technically wrong.

I also think its a bit odd to allow:

```js
  /**
   * @param {{ cause?: T }} [options]
   */
  constructor (options) {
    const { cause } = options || {};
```

But to ban:

```js
  /**
   * @param {{ cause?: T }} [options]
   */
  constructor ({ cause } = {}) {
```

See [this playground](https://www.typescriptlang.org/play?strictNullChecks=true&noUncheckedIndexedAccess=true&noUnusedLocals=true&noUnusedParameters=true&noFallthroughCasesInSwitch=true&exactOptionalPropertyTypes=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&useUnknownInCatchVariables=true&ts=4.8.0-dev.20220801&filetype=js#code/PQKhCgAIUgBAXAngBwKYBNUDNIHlnwCWA9gHYDOUMsyATsWrUpAN7ny2GkDmAvpAG0AtgENEAI1QBVUpixcMAXSrBw4UBGhxkI2iKGt8RMuX4CGxisuiqsAV1IBjS5Hip2AChbgAkKInSstgK6JAAvJAAROy0kQA04PwRLLwAlKy+8CIA1u4Ayhxc3B7+kjJyIakA3IlqGlTauvqGBCQUZhZt5NYgtg7Oba7u8ABMHp0m6d4+jibwGT5+YmVB8qQY4VEx8b5JkBMUkAA+R6y8NT5ZueQFnDwly4EV6+jVtepgDTRNBmyFPPwYipwPYnC4rvl-sUYlNfLMKMQADaoAB0iOI0I4b14ajcnjeeNGHmqQA) for an actual example of that.

I did check https://documentation.js.org/ and it will also infer that its optional if it has a default value, so in that way you are right, it is redundant, but I think it should be up to linters like [`eslint-plugin-jsdoc`](https://github.com/gajus/eslint-plugin-jsdoc) to point that out.

Also: The error message is not at all helpful in indicating that it is the redundant marking of optionality that is the issue here.

I think the fix of https://github.com/microsoft/TypeScript/issues/49869 is good, but I don't think this additional (unintended?) change is good.

**Comment by jespertheend** [comment]
While I don't really mind whether the duplicate marking of optionality is legal or not, the fact that this breaks existing code is probably less than ideal.
The fix is rather easy though, in my project I've had to remove the optionality from the jsdoc comment in 23 instances, which I don't think is too much of a pain.

If this does end up staying illegal, I do think the error message will have to be changed as mentioned above. The current error is indeed not very helpful.

**Comment by voxpelli** [comment]
Yeah, I'm also discovering more and more as I go + now adding cron tests for catching these failures in TS early.

Here's another example of mine: https://github.com/voxpelli/node-pg-pubsub/blob/7b988008ca4935cc2b256e5f42afaca51461cd1a/index.js#L26-L31

**Comment by voxpelli** [comment]
To ensure that this doesn't get lost, I added a proper regression report to the TS-repo: https://github.com/microsoft/TypeScript/issues/50286
